### ISSUE TITLE
How long should the utterances be?

### ISSUE THREAD

**Issue by janvainer** [yistLin/dvector#3]
Hi, awesome repo! I am wondering, how should I cut my data? Is this setup good for sentence-level utterances?
In the code, it seems that the model is trained on short chunks of voiced audio, but in the viasualization script, the embeddings are extracted from whole utterances (so a single embedding vector for the whole sentence). Did you experiment with different setups? For example, did you try to extract embeddings for segments of the given utterance and average them? My data is in an ASR setup, so it is pretty much sentence based. Any advice how to further segment such data? Regards, Jan

**Comment by yistLin** [comment]
Well, I think this setup is ok for sentence-level utterances.

Practically, for a long utterance, it should be segmented, embedded, and averaged to obtain a single fixed length embedding. The original paper also did these via sliding window segmentation (window size is around 200-frame long, and step size set to be half of the window size).

So I would definitely recommend you follow the settings in the original paper. Actually I also did the sliding window segmentation when I used the pretrained d-vector, but that part of code hasn’t been organized and pushed. Hope I’ll have some time to do this in the near future.

Regards,
Yist

**Comment by janvainer** [comment]
Hi, thanks for response. Would you recommend training the dvectors in the overlapping windows setup (paper setup), or do you think it is ok to leave the training as is - single vector without averaging and only do the segmentation, averaging etc at inference? Any experience with that based on your unpublished experiments? :) Btw I trained dvectors based on your repo and it works quite nicely! Thanks for nice code.

**Comment by yistLin** [comment]
If memory serves me, the authors applied the overlapping window setup **only at inference time**. So you could leave the training setup as is.
